In [7]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix

df = pd.read_csv('fruit_data_with_colors.txt', delimiter='\t')


In [8]:
df.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [9]:
df = df.drop(columns=['fruit_subtype','fruit_label','fruit_name'],axis=1)
df.head()

mass  width  height  color_score
0   192    8.4     7.3         0.55
1   180    8.0     6.8         0.59
2   176    7.4     7.2         0.60
3    86    6.2     4.7         0.80
4    84    6.0     4.6         0.79

In [10]:
k=4
def euclidian_distance(query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff)
        distance = np.sqrt(sum_sqrd_diff)
        return distance

In [11]:
train=np.array(df)

In [12]:
x=0
c=0
for y in train:
    print(train[x])
    x=x+1
    c=c+1
print(c)

[192.     8.4    7.3    0.55]
[180.     8.     6.8    0.59]
[176.    7.4   7.2   0.6]
[86.   6.2  4.7  0.8]
[84.    6.    4.6   0.79]
[80.    5.8   4.3   0.77]
[80.    5.9   4.3   0.81]
[76.    5.8   4.    0.81]
[178.     7.1    7.8    0.92]
[172.     7.4    7.     0.89]
[166.     6.9    7.3    0.93]
[172.     7.1    7.6    0.92]
[154.     7.     7.1    0.88]
[164.    7.3   7.7   0.7]
[152.     7.6    7.3    0.69]
[156.     7.7    7.1    0.69]
[1.0e+03 7.6e+00 7.5e+00 6.7e-01]
[168.     7.5    7.6    0.73]
[162.     7.5    7.1    0.83]
[162.     7.4    7.2    0.85]
[160.     7.5    7.5    0.86]
[156.     7.4    7.4    0.84]
[140.     7.3    7.1    0.87]
[170.     7.6    7.9    0.88]
[342.     9.     9.4    0.75]
[356.     9.2    9.2    0.75]
[362.     9.6    9.2    0.74]
[204.     7.5    9.2    0.77]
[140.     6.7    7.1    0.72]
[160.     7.     7.4    0.81]
[158.     7.1    7.5    0.79]
[210.     7.8    8.     0.82]
[164.    7.2   7.    0.8]
[190.     7.5    8.1    0.74]
[142.     7.

In [14]:
import plotly.express as px
fig=px.scatter(df,x='height',y='width')
fig.show()

ModuleNotFoundError: No module named 'plotly'

In [15]:
df.max()

mass           30000.00
width              9.60
height            10.50
color_score        0.93
dtype: float64

In [16]:
df.min()

mass           76.00
width           5.80
height          4.00
color_score     0.55
dtype: float64

In [17]:
k=4
w=np.random.randint(0,59,k)


In [18]:
w

array([34,  0, 26, 25])

In [19]:
centroids = train[w]
clusters = [[],[],[],[]]
clusters[0].append(w[0])
clusters[1].append(w[1])
clusters[2].append(w[2])
clusters[3].append(w[3])

In [21]:
for i in range(11):
    print('iter:',i+1, end = '\n')
    clusters = [[],[],[],[]]

    for x in train:
        id = np.argmin(euclidian_distance(x,centroids))
        clusters[id].append(x)

    c = np.array(clusters, dtype = object)

    for x in range(4):
        centroids[x] = np.mean(c[x], axis = 0)
        print(centroids[x])

    print()

iter: 1
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 2
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 3
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 4
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 5
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 6
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 7
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 8
[683.45762712   7.11355932   7.69491525   0.76305085]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]

iter: 9
[683.45762712   7.11355932   7.69491525   0.76305085]
[n