In [1]:

import numpy as np
import pandas as pd


from sklearn.metrics import confusion_matrix



In [2]:
a_dataframe = pd.read_csv("fruit_data_with_colors.txt",delimiter="\t")

In [134]:
a_dataframe


fruit_label fruit_name     fruit_subtype   mass  width  height  \
0             1      apple      granny_smith    192    8.4     7.3   
1             1      apple      granny_smith    180    8.0     6.8   
2             1      apple      granny_smith    176    7.4     7.2   
3             2   mandarin          mandarin     86    6.2     4.7   
4             2   mandarin          mandarin     84    6.0     4.6   
5             2   mandarin          mandarin     80    5.8     4.3   
6             2   mandarin          mandarin     80    5.9     4.3   
7             2   mandarin          mandarin     76    5.8     4.0   
8             1      apple          braeburn    178    7.1     7.8   
9             1      apple          braeburn    172    7.4     7.0   
10            1      apple          braeburn    166    6.9     7.3   
11            1      apple          braeburn    172    7.1     7.6   
12            1      apple          braeburn    154    7.0     7.1   
13            1      apple  golden_delicious    164    7.3     7.7   
14            1      apple  golden_delicious    152    7.6     7.3   
15            1      apple  golden_delicious    156    7.7     7.1   
16            1      apple  golden_delicious   1000    7.6     7.5   
17            1      apple  golden_delicious    168    7.5     7.6   
18            1      apple       cripps_pink    162    7.5     7.1   
19            1      apple       cripps_pink    162    7.4     7.2   
20            1      apple       cripps_pink    160    7.5     7.5   
21            1      apple       cripps_pink    156    7.4     7.4   
22            1      apple       cripps_pink    140    7.3     7.1   
23            1      apple       cripps_pink    170    7.6     7.9   
24            3     orange     spanish_jumbo    342    9.0     9.4   
25            3     orange     spanish_jumbo    356    9.2     9.2   
26            3     orange     spanish_jumbo    362    9.6     9.2   
27            3     orange  selected_seconds    204    7.5     9.2   
28            3     orange  selected_seconds    140    6.7     7.1   
29            3     orange  selected_seconds    160    7.0     7.4   
30            3     orange  selected_seconds    158    7.1     7.5   
31            3     orange  selected_seconds    210    7.8     8.0   
32            3     orange  selected_seconds    164    7.2     7.0   
33            3     orange      turkey_navel    190    7.5     8.1   
34            3     orange      turkey_navel    142    7.6     7.8   
35            3     orange      turkey_navel    150    7.1     7.9   
36            3     orange      turkey_navel    160    7.1     7.6   
37            3     orange      turkey_navel    154    7.3     7.3   
38            3     orange      turkey_navel    158    7.2     7.8   
39            3     orange      turkey_navel    154    7.3     7.5   
40            3     orange      turkey_navel  30000    7.1     7.5   
41            3     orange      turkey_navel    180    7.6     8.2   
42            3     orange      turkey_navel    154    7.2     7.2   
43            4      lemon    spanish_belsan    194    7.2    10.3   
44            4      lemon    spanish_belsan    200    7.3    10.5   
45            4      lemon    spanish_belsan    186    7.2     9.2   
46            4      lemon    spanish_belsan    216    7.3    10.2   
47            4      lemon    spanish_belsan    196    7.3     9.7   
48            4      lemon    spanish_belsan    174    7.3    10.1   
49            4      lemon           unknown    132    5.8     8.7   
50            4      lemon           unknown    130    6.0     8.2   
51            4      lemon           unknown    116    6.0     7.5   
52            4      lemon           unknown    118    5.9     8.0   
53            4      lemon           unknown    120    6.0     8.4   
54            4      lemon           unknown    116    6.1     8.5   
55            4      lemon           unknown    116    6.3     7.7   
56            

In [135]:
a_dataframe.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [136]:
x=a_dataframe[["mass","width","height"]]

In [137]:
x.head()

mass  width  height
0   192    8.4     7.3
1   180    8.0     6.8
2   176    7.4     7.2
3    86    6.2     4.7
4    84    6.0     4.6

In [138]:
y=a_dataframe[["fruit_label"]]
y

fruit_label
0             1
1             1
2             1
3             2
4             2
5             2
6             2
7             2
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            3
25            3
26            3
27            3
28            3
29            3
30            3
31            3
32            3
33            3
34            3
35            3
36            3
37            3
38            3
39            3
40            3
41            3
42            3
43            4
44            4
45            4
46            4
47            4
48            4
49            4
50            4
51            4
52            4
53            4
54            4
55            4
56            4
57            4
58            4

In [139]:
trainX=np.array(x[:50])              #first 50 from samples
trainY=np.array(y[:50])                # first 50 from labels
testX=np.array(x[50:])
testY=np.array(y[50:])

In [140]:
trainX

array([[1.92e+02, 8.40e+00, 7.30e+00],
       [1.80e+02, 8.00e+00, 6.80e+00],
       [1.76e+02, 7.40e+00, 7.20e+00],
       [8.60e+01, 6.20e+00, 4.70e+00],
       [8.40e+01, 6.00e+00, 4.60e+00],
       [8.00e+01, 5.80e+00, 4.30e+00],
       [8.00e+01, 5.90e+00, 4.30e+00],
       [7.60e+01, 5.80e+00, 4.00e+00],
       [1.78e+02, 7.10e+00, 7.80e+00],
       [1.72e+02, 7.40e+00, 7.00e+00],
       [1.66e+02, 6.90e+00, 7.30e+00],
       [1.72e+02, 7.10e+00, 7.60e+00],
       [1.54e+02, 7.00e+00, 7.10e+00],
       [1.64e+02, 7.30e+00, 7.70e+00],
       [1.52e+02, 7.60e+00, 7.30e+00],
       [1.56e+02, 7.70e+00, 7.10e+00],
       [1.00e+03, 7.60e+00, 7.50e+00],
       [1.68e+02, 7.50e+00, 7.60e+00],
       [1.62e+02, 7.50e+00, 7.10e+00],
       [1.62e+02, 7.40e+00, 7.20e+00],
       [1.60e+02, 7.50e+00, 7.50e+00],
       [1.56e+02, 7.40e+00, 7.40e+00],
       [1.40e+02, 7.30e+00, 7.10e+00],
       [1.70e+02, 7.60e+00, 7.90e+00],
       [3.42e+02, 9.00e+00, 9.40e+00],
       [3.56e+02, 9.20e+0

In [141]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        print("query", query.shape)
        #print(query)
        print("X",X.shape)
        #print(X)
        difference = np.array(X) - np.array(query)
        print("difference",difference.shape)
        #print(difference)
        sqrd_diff = np.square(difference)
        print("sqrd_diff",sqrd_diff.shape)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        print("sum_sqrd_diff",sum_sqrd_diff.shape)
        distance = np.sqrt(sum_sqrd_diff)
        print("distance",distance.shape)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        print("ed",ed.shape)
        nn = self.nearest_neighbours(ed)
        print("nn",nn.shape)
        labels_nn = list(trainY[nn])
        print("labels_nn",len(labels_nn))
        print(max(labels_nn, key = labels_nn.count))
        print("")
        return max(labels_nn, key = labels_nn.count) 

In [142]:
classifier = KNN(4)

predictions = [classifier.predict(x,trainX,trainY) for x in testX]
predictions

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
labels_nn 4
[3]

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
labels_nn 4
[3]

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
labels_nn 4
[3]

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
labels_nn 4
[3]

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
labels_nn 4
[3]

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
labels_nn 4
[3]

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
labels_nn 4
[3]

query (3,)
X (50, 3)
difference (50, 3)
sqrd_diff (50, 3)
sum_sqrd_diff (50,)
distance (50,)
ed (50,)
nn (4,)
l

[array([3], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64)]

In [143]:
trainX

array([[1.92e+02, 8.40e+00, 7.30e+00],
       [1.80e+02, 8.00e+00, 6.80e+00],
       [1.76e+02, 7.40e+00, 7.20e+00],
       [8.60e+01, 6.20e+00, 4.70e+00],
       [8.40e+01, 6.00e+00, 4.60e+00],
       [8.00e+01, 5.80e+00, 4.30e+00],
       [8.00e+01, 5.90e+00, 4.30e+00],
       [7.60e+01, 5.80e+00, 4.00e+00],
       [1.78e+02, 7.10e+00, 7.80e+00],
       [1.72e+02, 7.40e+00, 7.00e+00],
       [1.66e+02, 6.90e+00, 7.30e+00],
       [1.72e+02, 7.10e+00, 7.60e+00],
       [1.54e+02, 7.00e+00, 7.10e+00],
       [1.64e+02, 7.30e+00, 7.70e+00],
       [1.52e+02, 7.60e+00, 7.30e+00],
       [1.56e+02, 7.70e+00, 7.10e+00],
       [1.00e+03, 7.60e+00, 7.50e+00],
       [1.68e+02, 7.50e+00, 7.60e+00],
       [1.62e+02, 7.50e+00, 7.10e+00],
       [1.62e+02, 7.40e+00, 7.20e+00],
       [1.60e+02, 7.50e+00, 7.50e+00],
       [1.56e+02, 7.40e+00, 7.40e+00],
       [1.40e+02, 7.30e+00, 7.10e+00],
       [1.70e+02, 7.60e+00, 7.90e+00],
       [3.42e+02, 9.00e+00, 9.40e+00],
       [3.56e+02, 9.20e+0

In [144]:
testX

array([[130. ,   6. ,   8.2],
       [116. ,   6. ,   7.5],
       [118. ,   5.9,   8. ],
       [120. ,   6. ,   8.4],
       [116. ,   6.1,   8.5],
       [116. ,   6.3,   7.7],
       [116. ,   5.9,   8.1],
       [152. ,   6.5,   8.5],
       [118. ,   6.1,   8.1]])

In [145]:
x 

mass  width  height
0     192    8.4     7.3
1     180    8.0     6.8
2     176    7.4     7.2
3      86    6.2     4.7
4      84    6.0     4.6
5      80    5.8     4.3
6      80    5.9     4.3
7      76    5.8     4.0
8     178    7.1     7.8
9     172    7.4     7.0
10    166    6.9     7.3
11    172    7.1     7.6
12    154    7.0     7.1
13    164    7.3     7.7
14    152    7.6     7.3
15    156    7.7     7.1
16   1000    7.6     7.5
17    168    7.5     7.6
18    162    7.5     7.1
19    162    7.4     7.2
20    160    7.5     7.5
21    156    7.4     7.4
22    140    7.3     7.1
23    170    7.6     7.9
24    342    9.0     9.4
25    356    9.2     9.2
26    362    9.6     9.2
27    204    7.5     9.2
28    140    6.7     7.1
29    160    7.0     7.4
30    158    7.1     7.5
31    210    7.8     8.0
32    164    7.2     7.0
33    190    7.5     8.1
34    142    7.6     7.8
35    150    7.1     7.9
36    160    7.1     7.6
37    154    7.3     7.3
38    158    7.2     7.8
39    154    7.3     7.5
40  30000    7.1     7.5
41    180    7.6     8.2
42    154    7.2     7.2
43    194    7.2    10.3
44    200    7.3    10.5
45    186    7.2     9.2
46    216    7.3    10.2
47    196    7.3     9.7
48    174    7.3    10.1
49    132    5.8     8.7
50    130    6.0     8.2
51    116    6.0     7.5
52    118    5.9     8.0
53    120    6.0     8.4
54    116    6.1     8.5
55    116    6.3     7.7
56    116    5.9     8.1
57    152    6.5     8.5
58    118    6.1     8.1

In [146]:
cm = confusion_matrix(testY, predictions)
print(cm)

[[0 0]
 [9 0]]


In [147]:
acc = accuracy_score(predictions,testY)
print(acc)

0.0


In [148]:
cm = confusion_matrix(testY, predictions)
print(cm)

[[0 0]
 [9 0]]
